import Layout from "@/components/layout/layout";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "../redux/store";
import "@/styles/globals.css";
import "@/public/icomoon/style.css";
import { Roboto_Mono } from "next/font/google";
import Head from "next/head";
import SocketManager from "@/components/socketManager";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>CABLE ACCESSORIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/common/YY-LOGO-web.png" />
      </Head>
      <div className={`${roboto.className}`}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor || null}>
            <SocketManager />
            <Layout>
              <Component {...pageProps} />
            </Layout>
          </PersistGate>
        </Provider>
      </div>
    </>
  );
}
